### ISSUE TITLE
iOS ve Swift ile ilgili kaynaklar

### ISSUE THREAD

**Issue by halilozel1903** [mrabdullahsahin/ios-programlama-kaynaklar#1]
Merhabalar Swift dilini öğreniyorum ve yavaştan kısa kısa uygulamalar yapıyorum. 
Aşağıda karşılaştığım kaynakları ekleyeceğim. İnşallah yararlı olur.

**Github** 

Kendim çalışırken yazmış olduğum örnekleri ve açıklamaları aşağıdaki projelerde paylaşıyorum

- https://github.com/halilozel1903/Swift101
- https://github.com/halilozel1903/iOSProjects

**Medium**

Mediumda ise iOS ve Swift ile ilgili öğrendiğim bilgileri yazarak Türkçe kaynak oluşturmaya çalışıyorum.

- https://medium.com/@halilozel1903
- https://medium.com/@halilozel1903/ios-programlamada-gesture-recognizer-jest-alg%C4%B1lay%C4%B1c%C4%B1lar-kullan%C4%B1m%C4%B1-835450845680
- https://medium.com/@halilozel1903/ios-programlamada-image-view-kullan%C4%B1m%C4%B1-cb3455ed7e8b
- https://medium.com/@halilozel1903/ios-programlamada-alert-kullan%C4%B1m%C4%B1-db785adefaad
- https://medium.com/@halilozel1903/ios-programlama-da-segue-kullan%C4%B1m%C4%B1-2e291d9cc8ff
- https://medium.com/@halilozel1903/swift-4-i%CC%87le-objeler-kodla-nas%C4%B1l-tan%C4%B1mlan%C4%B1r-e25a8fd9815c
- https://medium.com/@halilozel1903/swift-4-de-diziler-arrays-in-kullan%C4%B1m%C4%B1-71ca8aed6dd4
- https://medium.com/@halilozel1903/swift-4-ile-ios-uygulamas%C4%B1-aydaki-k%C3%BCtlemiz-ne-kadar-73084561f838
- https://medium.com/@halilozel1903/swifti-tan%C4%B1yal%C4%B1m-a5a3a17820ef

**Udemy**

Udemyde ise iki adet beğendiğim eğitim var aşağıya onları ekliyorum.

- https://www.udemy.com/ios-11-swift-4-baslangictan-ileri-seviyeye-mobil-uygulama/learn/v4/
- https://www.udemy.com/swift-4-ile-baslangictan-ileri-seviyeye-mobil-uygulama-egitimi/learn/v4/

**Blog Yazıları**

Karşılaştığım iki adet blog yazıları yazılan siteyide paylaşıyorum.

- https://www.yazilimbilimi.org/category/programlama/swift/
- https://www.mobilhanem.com/category/swift-dersleri/

O listede olmayanları eklemeye çalıştım. İnşallah yararlı olur 👍

**Comment by mrabdullahsahin** [comment]
Selamlar,

Öncelikle katkılarından dolayı teşekkürler. Bu kaynakları bu repo'ya pull request atıp gerekli yerlere eklersen daha güzel olur. Örnek vermek gerekirse;

**Blog**
Halil Özel -> [Bağlantı](https://medium.com/@halilozel1903)

**Ücretli Kaynaklar**
iOS 11 Swift 4 Başlangıçtan İleri Seviyeye Mobil Uygulama -> [Bağlantı](https://www.udemy.com/ios-11-swift-4-baslangictan-ileri-seviyeye-mobil-uygulama/learn/v4/)

Saygılarımla,
Abdullah

**Comment by halilozel1903** [comment]
Merhabalar

pull request izin vermiyor başka bir branch açar mısınız ?

master dan master izin vermedi

**Comment by mrabdullahsahin** [comment]
Selamlar,

Kaynaklar eklenmiştir.

Saygılarımla,
Abdullah
